
kind: ConfigMap
apiVersion: v1
metadata:
  name: myconfigmapv1.0
  namespace: {{ .Values.microA.namespace }}
{{- if .Values.Env }}  
data:
{{- include "common.tplvalues.render" ( dict "value" .Values.Env "context" $ ) | nindent 2 }}
{{- end }}

{{- if .Values.microA.secretName }}
  CUSTOM_HEADER: 'Customized with a configmap! MicroA !! updated !! adding secret !! test Docker Hub'
{{- end }}
