kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.microA.configMapName }}
  namespace: {{ .Values.microA.namespace }}
data:
  BG_COLOR: '#12181b'
  FONT_COLOR: '#FFFFFF'
  CUSTOM_HEADER: 'Customized with a configmap! MicroA !! updated !!'
{{- if .Values.microA.secretName }}
envFrom:
  - secretRef:
      name: {{ .Values.microA.secretName }}
{{- end }}

