{{- $envData := .Values.env }}
{{- with $envData }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.microA.configMapName }}
  namespace: {{ .Values.microA.namespace }}
data:
{{- range $key, $value := fromYaml . }}
  {{ $key }}: "{{ $value }}"
{{- end }}

{{- if .Values.microA.secretName }}
  CUSTOM_HEADER: 'Customized with a configmap! MicroA !! updated !! adding secret'
{{- end }}
{{- end }}

