{{- range $microservice := .Values.microservices }}
{{- if $microservice.enabled }}
{{- $serviceAccount := index $microservice "serviceAccount" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include (printf "myapp1.%s.serviceAccountName" $microservice.name) $serviceAccount) .Chart.Name }}
 
  labels:
    app: {{ include "myapp1.fullname" . }}

{{- if $serviceAccount.annotations }}
  annotations:
{{ toYaml $serviceAccount.annotations | indent 4 }}
{{- end }}
{{- end }}
{{- end }}

