{{- range $key, $value := .Values }}
{{- if $value.enabled }}
{{- if $value.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "myapp1.serviceAccountName" $value) .Chart.Name }}
  
  annotations:
    {{- toYaml $value.serviceAccount.annotations | nindent 4 }}
automountServiceAccountToken: {{ $value.serviceAccount.automount }}
{{- end }}
{{- end }}
{{- end }}

