apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.microservices.microB.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: {{ .Values.microservices.microB.service.port }}
    protocol: TCP
    name: flask
  selector:
    app: {{ .Values.appName }}
    tier: frontend
  type: ClusterIP

