apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-microa
  namespace: {{ .Values.microA.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  replicas: {{ .Values.microA.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      tier: frontend
      microservice: microA
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: frontend
        microservice: microA
    spec: # Pod spec
      containers:
      - name: mycontainer
        image: {{ .Values.microA.image.name }}:{{ .Values.microA.image.tag }}
        ports:
        - containerPort: {{ .Values.microA.service.port }}
        envFrom:
        - configMapRef:
            name: {{ .Values.microA.configMapName }}
        resources:
          requests:
            memory: "16Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"

