apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-microb-service
  namespace: {{ .Values.microB.namespace }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: {{ .Values.microB.service.port }}
    protocol: TCP
    name: flask
  selector:
    app: {{ .Values.appName }}
    tier: frontend
    microservice: microB
  type: ClusterIP

