apiVersion: v1
kind: Secret
metadata:
    name: secret-microa
    namespace: default
type: Opaque
data:
    password: ENC[AES256_GCM,data:EOdpR6rYMXQ=,iv:Niyp8mILRkbHXyLr+buAYgjapLAvF1nzq9yf/b0tY2o=,tag:fksENRWgF1D6gRmLSQqGsA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-28T13:59:36Z"
    mac: ENC[AES256_GCM,data:KdOK3R1QvUzZXWajOX3UCkg/9qR0WcmZGnqSPL8hj0cfGkyoqlKTkr/TJw0hUYFlWZ09y6tlq9ZZGUvXpXl9Hld92h266vbXUx2NFDTZ+Sw7oxGRyPKCjBlQdM2a5zg6ochJ5QUQ33MKZeWJKv6Ifn8zFDdqxC7nu0qj5DKrP8I=,iv:I6hRU3wX3166M99npbiQy4h+jDE62RWdCYMAmW13XJg=,tag:tTesH0A1YMnHZUEd+6+Abw==,type:str]
    pgp:
        - created_at: "2024-02-28T13:59:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA8HcuuBtZq88AQv/YWnijnRXvXxhPh5L0J2ElGEl3pdj9nsdPYab+P5qef+d
            VW4Nk/AdYWqGeUHylYH6HlmK9QhEXyjwrKHsOxMw2w7xOJsZcEmbOvM8v9O9zuCk
            gmNtHIcAPjmf1TroxxnW5K4tn/uHLqWq4k8RoYg8Q0+TinOgqazl8thATtbpfwPN
            Pz0McFu2WMMcv/lw1JElDgn1BA37ZQfbtpaOPacYUA1UZZc0jCCUsXGy/3PyZdIc
            Q8Z/t9n2FYjgPWhl+yiXvBLBXkRkNKTHOO3a48HRkx9MzL3bucXcuxL216EQj95P
            Ly874PERBFmrQ14OB9w6QfuyFNDhwMr/ZnNl41W++NTAjejvf4t78KPcXXiGEbkJ
            y88jZddkhsuLxTqICpUE66/3CaJwRRfy1rIaFCdO0rlhDat+DkU/6ysk8YmLosa7
            qqswy+IjjcMphLQX6ESUwx+c+4zKRVT3SwVzMTlapvRSrtg8DLa3FK+kiySSrvsr
            ZNaZyfGRVlbULLj4jfXY0l4BGxuqkPDX0V0drPo3Dc76kzqBCJLeIu9YuVXoyM6f
            /HvaqM/PTEVXbParVpp3092mGKTsmTY9ZiOlqjmmhiFUwZODUx7c+Enu1WJb0roY
            UEqy3OvjBwlAO1LqSOYU
            =rgkw
            -----END PGP MESSAGE-----
          fp: C27C7EF543D4DFA0DAB20C6EDB75A20BFE8BF81A
    encrypted_regex: ^(users|data|stringData)$
    version: 3.7.3
