apiVersion: ENC[AES256_GCM,data:ln8=,iv:IViw/9AX8NptTXn/RHYwkTA+vO23jVm3yj309KmnKc8=,tag:NX5nWk8K6SdD1BL52CJO6g==,type:str]
kind: ENC[AES256_GCM,data:RVkSgh+n,iv:Z7jGpngBr7AxPDL0c/HLUm6HlQXWCwt1c5RxjfotxXo=,tag:30pc7sXwusPPXj3q0s5JpA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:BWYMfbZsx1soEwZJFQ==,iv:Qxr58lkm8PAWZLSMd1lFoK1vj+GYUmrBSw1ZYBmtyd0=,tag:a0wwCX7pYCbxnBXMbW2xUg==,type:str]
    namespace: ENC[AES256_GCM,data:ItuNFbl/ow==,iv:ReyuUpEEj7z63E3bpMoK7ipzaAhMPRixjdw4StJ/RAg=,tag:UnQ3uD7pbgak1zD3MLXD5g==,type:str]
type: ENC[AES256_GCM,data:QTlHM8oP,iv:PZSB9baO2FqYfHWeY8+jKqU4aW6PwiXv8iPBaedhFcM=,tag:COi+VuaRRmopBkc1eJEO9w==,type:str]
data:
    password: ENC[AES256_GCM,data:SwD54sHf/0E=,iv:wtMoqV1BE5r7l0BCsZQzKvhYQk3vDZYlNHnzOt98/WM=,tag:G9b3idJJ8R768sKDp1ZORA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-02-27T08:54:47Z"
    mac: ENC[AES256_GCM,data:LNQTORLG/ovkP57E7kUNYu//VxzNHcR5TmhBRMRIS3V3LiNITKe3ghEsDRPr06jhRb41DN6qSX87j7EMHGbaMrostXt0oVYI0ExGIWzXo+H2OZNWhiSg1jQYInMSM1HI0CyN+Yp/QxLqCgidxYVnsTbV5sXP7U8F/zcLXDOmk90=,iv:hfYrekztUSXfpV7WYKlaCmMGzcldnUqEXKJY9f4pO+k=,tag:9GDLQMpfsRiE4qR2AG3ZTw==,type:str]
    pgp:
        - created_at: "2024-02-27T08:54:46Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA4JiMRI7Vx4rAQ/+L4HNQwnipKjzs3QhgGOL8fJWqHjKq3yBimLQM8EAepMt
            5VJMtLhQFPMS8HtD6QYg1TpBPptCpt/0Ib6naiuF+VpegKYSRQagK3whWETEQZ+4
            GlegYh++A/1Kmo49dXRKxsHbvvewT30M2Le4uBd78mWEG8D0tIhurw+Xl8xsYgLN
            eKYL/Q2GyRgWQa3un8jDknUNZEpf4xycV8R3L55uE+8qAVztWiMGSJ6CIh/50cJl
            vSHfQTIFig2LQ49Qw3E/0wpb4NySJ+WiZsam5xTmiskfTs9c9842a7HXs2BqxhuR
            OGW7yiMlfkPOCZ9MrfjkC2icgboP8GQ6GFM418Z4/0ThPQgDcndVL6odstSpDQUu
            y16uD54UL7D1wGoNEJ063HrghcwhXXoCzZf5TJVVB9iR+OYtQXtDKU0mbSw/Vs+2
            1W8M91smsVD8yxo8hLKCsBoxaAhkmPzCAHn6bcGKUyGw1ZR7o4V7Tmt2sWHTMI5M
            NP9C701Lt+KnwJauxrjDsEwqj3l8k/Y7JDARJPtLCIXJUId3HaPKAeWwNskAeUbP
            0iAjbc6z+b5AwnPxp0+kDIi+sPDTQfWYqABNhasgDpKg/YRcYkq01PRVwl/5Otz0
            04vLqkK5HzeMVQmluHKJ1fxUNMpy4oEnbmZ8tUQWTIudMiYoeG8l6c+IG5KtK/HS
            XAFWxdsR79rIkNA4Atwj9lLOWYa6RvX2hUwqEmCZr81KhaAROH5ej0ZHy8lF8fI9
            LYmU8koFSbYjbl31Ngt6ls3F1WA+pRmxB1cf78Y/x4qPyscgUXTH5y/+Ie3o
            =W8KA
            -----END PGP MESSAGE-----
          fp: 5D5EA4595BFB0ADE512EBBDD9D03DB5266DD26F9
    unencrypted_suffix: _unencrypted
    version: 3.7.3
